### ISSUE TITLE
Windows On Arm64, support?

### ISSUE THREAD

**Issue by sidd-kishan** [NVIDIA/open-gpu-kernel-modules#106]
**NVIDIA Driver Version**
Please write the version of the NVIDIA driver you are using.

**GPU**
Please write the particular model of NVIDIA GPU you are using.

**Describe the bug**
Please write a clear and concise description of what the bug is.

**To Reproduce**
Please write the steps to reproduce the behavior.

**Expected behavior**
Please write a clear and concise description of what you expected to happen.

**Please reproduce the problem, run nvidia-bug-report.sh, and attach the resulting nvidia-bug-report.log.gz.**

**Comment by sidd-kishan** [comment]
Please let us know when can we have an ARM64 version for Windows on ARM OS.

**Comment by aritger** [comment]
It is very unlikely any future Windows on Arm64 support would use the open-gpu-kernel-modules in this repository.  I think we need to keep the issue tracker here focused on bugs/requests pertaining to the open-gpu-kernel-modules.  Closing, sorry.

**Comment by aritger** [comment]
I'm sorry, but I'm going to stick to my previous comment:

"It is very unlikely any future Windows on Arm64 support would use the open-gpu-kernel-modules in this repository. I think we need to keep the issue tracker here focused on bugs/requests pertaining to the open-gpu-kernel-modules."

It is a fair request for NVIDIA to support its Windows GPU driver on ARM64, but the open-gpu-kernel-modules github repo is not the right place to track that request.  Maybe ask on https://forums.developer.nvidia.com/

**Comment by VOM7HC** [comment]
thank you for reply to me, please help update if you can have any new update for us. Happy coding new week
