### ISSUE TITLE
trunk/src/common/displayport/src/dp_configcaps.cpp:405: array index sanity check in wrong place ?

### ISSUE THREAD

**Issue by dcb314** [NVIDIA/open-gpu-kernel-modules#110]
Static analyser cppcheck says:

trunk/src/common/displayport/src/dp_configcaps.cpp:405:55: style: Array index 'i' is used before limits check. [arrayIndexThenCheck]

Source code is

                   for (int i = 0; caps.linkRateTable[i] && (i < NV_DPCD_SUPPORTED_LINK_RATES__SIZE); i++)

Suggest move sanity check from after use, to before use.

**Comment by aaronp24** [comment]
Thanks for reporting this. I filed internal bug number 3643714 to track this.
