### ISSUE TITLE
(suggestions) use a linter in your internal dev environment

### ISSUE THREAD

**Issue by ghtesting2020** [NVIDIA/open-gpu-kernel-modules#115]
I'm seeing dozens of tickets that could be avoided if Nvidia used a linter in their own internal dev environment. GitHub Actions could also be implemented to autocheck code for compliance, security issues, quality, etc. At my work we use cppcheck for static code analysis and it's been amazing so far. SonarQube/Lint is also an option as well as being open source/free.

**Comment by PAR2020** [comment]
@ghtesting2020 thanks for the suggestion, will look into it.

**Comment by Tachi107** [comment]
Duplicate of #27

**Comment by mmaneetsingh** [comment]
Thank you for the suggestion @ghtesting2020. I have consolidated your feedback in #27 (thanks @Tachi107) and closing this issue.
