### ISSUE TITLE
*BSD's drivers in the future?

### ISSUE THREAD

**Issue by Mattio-cmd** [NVIDIA/open-gpu-kernel-modules#121]
Now that there is work on making a driver for linux, is there any consideration in doing so with the popular BSD's (NetBSD, FreeBSD, OpenBSD)

**Comment by brxken128** [comment]
i hope so. i don't think Net/OpenBSD have NVIDIA drivers, but open sourcing the FreeBSD ones would be immeasurably helpful to the community.

**Comment by mtijanic** [comment]
Hello, welcome and thank you for your interest! Please see #47 for relevant info. I'm going to close this issue as a duplicate and let's use that one for further discussion on this topic.

Thanks.
