### ISSUE TITLE
What are the SMC features of the GPU?

### ISSUE THREAD

**Issue by s66104444** [NVIDIA/open-gpu-kernel-modules#143]
I see in the code that the GPU seems to have the ability to be partitioned into multiple vGPUs if SMC is enabled, anyway, I'm curious as to what exactly SMC means.

**Comment by pityulaxd** [comment]
Not expert.
It seems its a Smart Memory Controller on the gpu itself, so i think on higher end cards they have the chip and than it support virtualization of memory.
Other than that this is what a search got me on it: https://www.supermicro.com/solutions/NVIDIA_vGPU_Virtual_Desktop_Reference_Architecture.pdf

**Comment by mtijanic** [comment]
Hello and thank you for your interest!

SMC stands for "Simultaneous Multiple Contexts" and is a feature also known as MIG (Multi Instance GPU). Please see the [Ampere architecture whitepaper](https://images.nvidia.com/aem-dam/en-zz/Solutions/data-center/nvidia-ampere-architecture-whitepaper.pdf) for more details.

> The new Multi-Instance GPU (MIG) feature allows the A100 Tensor Core GPU to be securely
> partitioned into as many as seven separate GPU Instances for CUDA applications, providing
> multiple users with separate GPU resources to accelerate their applications and development
> projects.

**Comment by s66104444** [comment]
Thanks! Help me a lot!

**Comment by mtijanic** [comment]
Closing this, let's use #148 to consolidate all similar questions. Thanks!
