### ISSUE TITLE
src/common/displayport/src/dp_configcaps.cpp:2866: defective error checking ?

### ISSUE THREAD

**Issue by dcb314** [NVIDIA/open-gpu-kernel-modules#173]
Static analyser cppcheck says:

src/common/displayport/src/dp_configcaps.cpp:2866:32: style: Same expression on both sides of '&&'. [duplicateExpression]

Source code is

       if (bLinkReady == NULL && bLinkReady == NULL)

Maybe better code:

       if (bLinkActive == NULL && bLinkReady == NULL)

**Comment by Leseratte10** [comment]
That's already been reported in #56

**Comment by aritger** [comment]
Closing as duplicate.
