### ISSUE TITLE
src/nvidia/arch/nvalloc/unix/src/osapi.c:4589: broken error checking ?

### ISSUE THREAD

**Issue by dcb314** [NVIDIA/open-gpu-kernel-modules#174]
Static analyser cppcheck says:

src/nvidia/arch/nvalloc/unix/src/osapi.c:4589:50: style: Same expression on both sides of '||'. [duplicateExpression]

Source code is

    if ((pNid == NULL) || (pNumaMemAddr == NULL) || (pNumaMemAddr == NULL))

Maybe some other input parameter should be checked ?

**Comment by maximilianovermeyer** [comment]
duplicate of #55

**Comment by PAR2020** [comment]
dup of PR #61
