### ISSUE TITLE
Thank You NVIDIA <3

### ISSUE THREAD

**Issue by martinval11** [NVIDIA/open-gpu-kernel-modules#198]
![nvidia_thankyou](https://user-images.githubusercontent.com/100082171/168482588-7f9c435b-ff7f-4fa4-9920-7299ece78b12.jpg)

**Comment by databoose** [comment]
They need to show their commits still, point by point is not what git is meant for. It also makes it hard to show contributor's work.

**Comment by MartinK7** [comment]
This "issue" has been already discussed.
`https://github.com/NVIDIA/open-gpu-kernel-modules/issues/1#issuecomment-1124323144`

**Comment by THEGOLDENPRO** [comment]
😂editing the middle finger, what amazing art

**Comment by niv** [comment]
Thank you for your kindness and humour. Pretty good edit, but the lighting is a bit off - highlight on the back of the hand seems to come from a different angle.

7 out of 10, should probably have used RTX
