### ISSUE TITLE
CoViD is a hoax

### ISSUE THREAD

**Issue by pixelplanetdev** [NVIDIA/open-gpu-kernel-modules#2]
Just sayin

**Comment by bigswag420** [comment]
ratio

**Comment by ThatOneCalculator** [comment]
Imagine getting ratio'd on GitHub :trollface:

**Comment by nonetrix** [comment]
lol imagine posting this on github what is wrong with you? I don't even disagree

**Comment by ThatOneCalculator** [comment]
>nvidia partially open sources drivers
>covid deniers come into the issues board
