### ISSUE TITLE
Make script fails at 'make -C kernel-open modules'

### ISSUE THREAD

**Issue by ofeeg** [NVIDIA/open-gpu-kernel-modules#284]
### NVIDIA Open GPU Kernel Modules Version

main

### Operating System and Version

Debian GNU/Linux bookworm/sid

### Kernel Release

Linux 5.17.0-3-amd64 #1 SMP PREEMPT Debian 5.17.11-1 (2022-05-26) x86_64 GNU/Linux

### Build Command

make modules -j8

### Terminal output/Build Log

 [ nvidia            ]  CC           ../common/uproc/os/libos-v2.0.0/debug/logdecode.c
In file included from inc/kernel/core/printf.h:38,
                 from inc/kernel/core/prelude.h:44,
                 from src/kernel/rmapi/nv_gpu_ops.c:24:
src/kernel/rmapi/nv_gpu_ops.c: In function ‘nvGpuOpsDeviceCreate’:
inc/libraries/utils/nvprintf.h:305:30: warning: ‘linkBandwidthMBps’ may be used uninitialized [-Wmaybe-uninitialized]
  305 | #define NVRM_PRINTF_FUNCTION nvDbg_Printf
      |                              ^
inc/libraries/utils/nvprintf.h:316:6: note: in expansion of macro ‘NVRM_PRINTF_FUNCTION’
  316 |      NVRM_PRINTF_FUNCTION(NV_FILE_STR, __LINE__, NV_FUNCTION_STR, level, format, ##__VA_ARGS__)
      |      ^~~~~~~~~~~~~~~~~~~~
inc/libraries/utils/nvprintf.h:255:9: note: in expansion of macro ‘NV_PRINTF_STRING’
  255 |         NV_PRINTF_STRING(module, level, format, ##__VA_ARGS__);             \
      |         ^~~~~~~~~~~~~~~~
inc/libraries/utils/nvprintf.h:231:5: note: in expansion of macro ‘NV_PRINTF_EX’
  231 |     NV_PRINTF_EX(NV_PRINTF_MODULE, level, NV_PRINTF_ADD_PREFIX(format), ##__VA_ARGS__)
      |     ^~~~~~~~~~~~
src/kernel/rmapi/nv_gpu_ops.c:1772:5: note: in expansion of macro ‘NV_PRINTF’
 1772 |     NV_PRINTF(LEVEL_INFO, "sysmem link type: %d bw: %u\n", sysmemLink, linkBandwidthMBps);
      |     ^~~~~~~~~
src/kernel/rmapi/nv_gpu_ops.c:1636:11: note: ‘linkBandwidthMBps’ declared here
 1636 |     NvU32 linkBandwidthMBps;
      |           ^~~~~~~~~~~~~~~~~
 [ nvidia            ]  CC           _out/Linux_x86_64/g_nvid_string.c
 [ nvidia            ]  LD           _out/Linux_x86_64/nv-kernel.o
 [ nvidia            ]  OBJCOPY      _out/Linux_x86_64/nv-kernel.o
make[1]: Leaving directory '/home/mrhan/open-gpu-kernel-modules/src/nvidia'
cd kernel-open/nvidia/ && ln -sf ../../src/nvidia/_out/Linux_x86_64/nv-kernel.o nv-kernel.o_binary
make -C kernel-open modules
make[1]: Entering directory '/home/mrhan/open-gpu-kernel-modules/kernel-open'
make[2]: Entering directory '/home/mrhan/open-gpu-kernel-modules/kernel-open'
make[2]: *** /lib/modules/5.17.0-3-amd64/build: No such file or directory.  Stop.
make[2]: Leaving directory '/home/mrhan/open-gpu-kernel-modules/kernel-open'
make[1]: *** [Makefile:82: modules] Error 2
make[1]: Leaving directory '/home/mrhan/open-gpu-kernel-modules/kernel-open'
make: *** [Makefile:50: modules] Error 2

**Comment by aritger** [comment]
I'm pretty sure the problem here is missing kernel header files.  So, I'm going to go ahead and close this.  Please reopen if you find that isn't the case.
