### ISSUE TITLE
Screen Flickering on dGPU mode, Lenovo Legion Y740

### ISSUE THREAD

**Issue by AgnaySrivastava** [NVIDIA/open-gpu-kernel-modules#288]
### NVIDIA Open GPU Kernel Modules Version

nvidia-open-dkms-515.43.04-9

### Does this happen with the proprietary driver (of the same version) as well?

Yes

### Operating System and Version

Arch Linux

### Kernel Release

Linux y740 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000 x86_64 GNU/Linux  (Its the stock Linux Kernel))

### Hardware: GPU

GPU 0: NVIDIA GeForce RTX 2070 with Max-Q Design (UUID: GPU-0ce98c07-b155-c369-66cf-0054d4c4af53)

### Describe the bug

I own a Lenovo Legion Y740-15 IRHg with an i7-9750h + RTX 2070 Max-Q. My laptop has a mux switch that lets me switch between: 

1.  Dedicated GPU mode (Nvidia optimus off):  Where the Integrated Graphics card is turned off, leaving only the nvidia card in use,  which allows for better performance and enables me to use gsync at the cost of significantly lesser battery life.
2. Hybrid mode (Nvidia optimus on): Both GPUs are turned on and this helps improve battery life at the cost of performance.

- On Hybrid mode everything works, there is no flickering whatsoever. Everything listed on the arch wiki concerned with nvidia-optimus works fine from [here:](https://wiki.archlinux.org/title/NVIDIA_Optimus)

- On DGPU mode however, the greated the system load, the greater the screen flicker. Things I have tried to resolve this issue (obviously none of them work):  
1.  Blacklisting nouveau drivers.
2. Forcing Full composition pipeline in nvidia-settings.
3. Using the DKMS version of the driver.
4. Changing DRM kernel mode setting to 1. From [here](https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting) 
5. Using older versions of my laptop's BIOS.

### To Reproduce

- Install any current version of the proprietary or open source drivers from the official arch repos on a Lenovo Legion Y740-15 IRHg. Dkms or non-dkms does not matter as the issue persists with both. I have used the nvidia-open-dkms-515.43.04-9 package.
- Perform any demanding task that increases system load such as compilation, running a video game or playing a video in higher res.
- The screen flickers while the load is high and then reduces once the aforementioned demanding tasks have been completed. 

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/NVIDIA/open-gpu-kernel-modules/files/8844380/nvidia-bug-report.log.gz)

### More Info

- **Windows Had a similar problem back in September 2020 for the y740 that started with the release of driver 456.38 but that was promptly fixed through a driver update.** 
- Somebody else replied to my thread on the nvidia forums [here:](https://forums.developer.nvidia.com/t/screen-flicker-tear-on-mux-laptop/180631)  and i quote him and [his forum post](https://forums.developer.nvidia.com/t/latest-nvidia-drivers-for-linux-using-2-lanes-8-10-gbps-instead-of-4-lanes-5-40-gbps-for-1080p-144hz/195615) underneath: 
- I am experiencing the same issue, with any driver after version 450.119 in any Linux distro. **The root cause is the Nvidia driver identifying the connection between display and gpu as DP 1.4 instead of DP 1.2 and sending higher bitrate signal on it.**  
- Screenshots of the working and buggy drivers respectively can be found [here:](https://imgur.com/a/e2Z7tfz).

It would be great if any developers working on Nvidia Linux drivers could only take notice as the above issue seems fairly easy to resolve. Thanks in advance to anyone who can shed light on this issue!

**Comment by amrit1711** [comment]
Hello Agnay,
Thanks for writing the problem to us. As per problem description, it is not specific to Open GPU Kernel Modules components.
Moreover, you have also reported issue through linux-bugs@nvidia.com which is acknowledged and shall be worked upon.
With due respect, I will close this issue and shall continue using the forum for these types of problems/discussions.
