### ISSUE TITLE
Higher power consumption in idle for a high refresh monitor vs. Windows

### ISSUE THREAD

**Issue by birdie-github** [NVIDIA/open-gpu-kernel-modules#362]
### NVIDIA Open GPU Kernel Modules Version

515.65.01

### Does this happen with the proprietary driver (of the same version) as well?

Yes

### Operating System and Version

Fedora release 36 (Thirty Six)

### Kernel Release

5.19.7

### Hardware: GPU

NVIDIA GeForce GTX 1660 Ti

### Describe the bug

I have a 144Hz FreeSync/GSync compatible monitor.

When it's running at its native refresh rate, 144Hz, under XFCE4 (compositing **disabled**) NVIDIA reports ~10.5W idle power consumption. When it's running at 60Hz, its power consumption drops to around ~9.5W.

Under Windows **regardless** of the refresh rate, its power consumption in idle is around ~8.9W.

Would be great if the Linux driver could be optimized to have the idle power consumption comparable to Windows.

### To Reproduce

1. Have a high refresh rate monitor.
2. `watch nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits`
3. Switch between refresh rates e.g. using `xrandr`:

* `xrandr --output DP-2 --rate 144.0 --primary --mode 2560x1440`
* `xrandr --output DP-2 --rate 60.0 --primary --mode 2560x1440`

### Bug Incidence

Always

### nvidia-bug-report.log.gz

N/A

### More Info

This is a bug report against the proprietary driver (since reports at https://forums.developer.nvidia.com/c/gpu-graphics/linux/148 are largely ignored). The Open Source driver has abysmal power management at the moment.

Source: https://forums.developer.nvidia.com/t/insufficient-power-gating-for-high-resolution-high-refresh-rate-modes-in-linux-vs-windows/203852

**Comment by amrit1711** [comment]
I have filed a bug 3786462  internally for tracking purpose.
I will close this thread as this issue is not specific to open GPU kernel modules.
Shall keep updated devtalk forum with the progress.
