### ISSUE TITLE
GravityMark GPU Benchmark in OpenGLES mode totally breaks NVIDIA drivers, Xid 13

### ISSUE THREAD

**Issue by birdie-github** [NVIDIA/open-gpu-kernel-modules#364]
### NVIDIA Open GPU Kernel Modules Version

515.65.01

### Does this happen with the proprietary driver (of the same version) as well?

Yes

### Operating System and Version

Fedora release 36 (Thirty Six)

### Kernel Release

5.19.7

### Hardware: GPU

NVIDIA GeForce GTX 1660 Ti

### Describe the bug

GravityMark GPU Benchmark in OpenGLES mode totally breaks NVIDIA drivers

### To Reproduce

1. `wget https://tellusim.com/download/GravityMark_1.70.run`
2. `bash GravityMark_1.70.run`
3. `Ctrl+C` several times to exit it
4. `cd GravityMark_1.70_linux`
5. `./run_windowed_gles.sh`

### Bug Incidence

Always

### nvidia-bug-report.log.gz

Applies to all NVIDIA GPUs.

### More Info

```
NVRM: Xid (PCI:0000:08:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: SKEDCHECK03_LOCAL_MEMORY_HIGH_SIZE failed
NVRM: Xid (PCI:0000:08:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: SKEDCHECK05_LOCAL_MEMORY_TOTAL_SIZE failed
NVRM: Xid (PCI:0000:08:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: SKEDCHECK06_REGISTER_COUNT failed
NVRM: Xid (PCI:0000:08:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: SKEDCHECK13_PROGRAM_OFFSET failed
NVRM: Xid (PCI:0000:08:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: SKEDCHECK16_CTA_THREAD_DIMENSION_ZERO failed
NVRM: Xid (PCI:0000:08:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: ESR 0x407020=0x903400 0x407028=0x1000 0x40702c=0x9ce50 0x407030=0x0
NVRM: Xid (PCI:0000:08:00): 13, pid=424294, name=GravityMark.x64, Graphics Exception: ChID 0028, Class 0000c5c0, Offset 00000000, Data 00000000
NVRM: Xid (PCI:0000:08:00): 32, pid=424294, name=GravityMark.x64, Channel ID 00000028 intr 00200000
```

This is a crosspost from https://forums.developer.nvidia.com/t/bug-report-gravitymark-gpu-benchmark-in-opengles-mode-totally-breaks-nvidia-drivers/181025 which was totally ignored. This is a bug report against the proprietary driver.

**Comment by amrit1711** [comment]
@birdie-github 
I have filed a bug 3785752 internally for tracking purpose.
I will close this thread as it is not specific to open GPU kernel modules.
However, I will keep updating on devtalk forum for further updates.
