### ISSUE TITLE
CPU spikes and overall sluggishness

### ISSUE THREAD

**Issue by Enlinks** [NVIDIA/open-gpu-kernel-modules#398]
### NVIDIA Open GPU Kernel Modules Version

515

### Does this happen with the proprietary driver (of the same version) as well?

No

### Operating System and Version

Ubuntu 22.10

### Kernel Release

5.19.0-23-generic

### Hardware: GPU

NVIDIA T1200 Laptop GPU

### Describe the bug

Noticed overall sluggishness in system along with what appears to be ~5-10 sec hang on the Lenovo boot screen after entering my encryption key.

It's slightly noticable in general use but the biggest issue was seen when trying to stream Plex and was seeing very choppy video.

Additionally top is showing gnome-shell process having 100 CPU spikes every 10 or so seconds.

As soon as I switch back to the closed kernel 515 I don't see any of these problems anymore.

### To Reproduce

I can repo this by switching my system back to the open 515 driver. I'm unsure if this is something unique to my system but will switchback to collect whatever is needed.

### Bug Incidence

Always

### nvidia-bug-report.log.gz

I'm attaching the report from the working closed 515 driver, will upload the open 515 driver after this is submitted.

**Comment by Enlinks** [comment]
[closed-515-nvidia-bug-report.log.gz](https://github.com/NVIDIA/open-gpu-kernel-modules/files/9881432/closed-515-nvidia-bug-report.log.gz)

**Comment by Enlinks** [comment]
So it seems the system isn't reconzing the GPU with the open 515 driver:
```
nvidia-smi -L
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```
[open-515-nvidia-bug-report.log.gz](https://github.com/NVIDIA/open-gpu-kernel-modules/files/9881485/open-515-nvidia-bug-report.log.gz)

**Comment by aritger** [comment]
I suspect it is this:
```
Oct 26 06:43:32 enlinks-ThinkPad-P1-Gen-4i kernel: [    3.892509] NVRM: Open nvidia.ko is only ready for use on Data Center GPUs.
Oct 26 06:43:32 enlinks-ThinkPad-P1-Gen-4i kernel: [    3.892511] NVRM: To force use of Open nvidia.ko on other GPUs, see the
Oct 26 06:43:32 enlinks-ThinkPad-P1-Gen-4i kernel: [    3.892512] NVRM: 'OpenRmEnableUnsupportedGpus' kernel module parameter described
Oct 26 06:43:32 enlinks-ThinkPad-P1-Gen-4i kernel: [    3.892513] NVRM: in the README.
```
Do things work better if you set that kernel module parameter?

**Comment by Grimish-ng** [comment]
You have 'options nvidia NVreg_OpenRmEnableUnsupportedGpus=1' enabled?

**Comment by Enlinks** [comment]
@aritger thank you for the reply!

So I did some more digging around as I was having issues applying that via modprobe.
```
modprobe: ERROR: could not insert 'nvidia': Key was rejected by service
```

Further digging I actually found that the module wasn't being loaded per dmesg (assumed)
```
Loading of unsigned module is rejected
```

I attempted to follow this [guide](https://ubuntu.com/blog/how-to-sign-things-for-secure-boot) from Ubuntu to manually sign the modules as I was able to confirm (also with that guide) that the modules were not signed. However after manually signing them with kmodsign and that brought up further issues when trying to update initramfs with a "Exec format error" on all of the nvidia modules.

I ended up purging all of my Nvidia and Nouveau drivers and then after reboot I disabled the display manager (got the idea from [here](https://unix.stackexchange.com/questions/440840/how-to-unload-kernel-module-nvidia-drm)). Lastly, followed the Nvidia [README](https://download.nvidia.com/XFree86/Linux-x86_64/515.65.01/README/installdriver.html#modulesigning) on how to sign the modules and just used the existing certs I already had on the system from Ubuntu (I'm using secure boot due to needing it on my Windows install on the other NVMe). 

```
sudo sh ./NVIDIA-Linux-x86_64-515.65.01.run -s --module-signing-secret-key=/var/lib/shim-signed/mok/MOK.priv --module-signing-public-key=/var/lib/shim-signed/mok/MOK.der
```

After that I rebooted again and with my very buggy UI I used the Ubuntu Drivers tool to load up the 515 open drivers and rebooted again. After this everything was working as intended, I have some other issues I'm seeing in the logs but not seeing the same issues this post was made for.



The last thing I want to point out and I don't know if this is correct or may cause issues in the future? It seems that pre/post the nvidia modules are not in the same directories as they were before. My unsigned modules were all located in "/lib/modules/5.19.0-23-generic/updates/dkms/" however post all this work that no longer exists and they are now located in "/lib/modules/5.19.0-23-generic/kernel/nvidia-515/" along with all of the .sig filed for the other drivers like 520.

**Comment by Enlinks** [comment]
Noticed that while there are drivers are in a different directories, there is another set of drivers under "lib/modules/5.19.0-23-generic/kernel/drivers/video/" which are actually being used instead.
```
sudo modinfo nvidia
filename:       /lib/modules/5.19.0-23-generic/kernel/drivers/video/nvidia.ko
firmware:       nvidia/515.65.01/gsp.bin
```

Both sets of drivers are all signed and I can only see a minor difference from a hexdump. Overall I think this was user error on my part by overlooking some things or a Ubuntu issue with not properly installing the new drivers once I attempted to switch to the open module via the Drivers tool.

**Comment by aritger** [comment]
Thanks, @Enlinks.  I'm glad you have things working, now.

Signing kernel modules, particularly out of tree kernel modules, is tricky.

I suspect /lib/modules/5.19.0-23-generic/kernel/drivers/video/nvidia.ko is installed from the .run file, while /lib/modules/5.19.0-23-generic/kernel/nvidia-515/ sounds like it came from an Ubuntu package.

I'm not very familiar with Ubuntu's repackagings of the NVIDIA driver, but ultimately that is probably going to be a better thing to use.  The typical problem people trip on is that when they update their kernel through the distro package manager, the .run-installed NVIDIA kernel modules will require re-installation.

So, you may want to revisit Ubuntu's repackagings, or at least look at registering with dkms:

https://download.nvidia.com/XFree86/Linux-x86_64/515.65.01/README/installdriver.html#RegisteringTheNda02d

In any case, it sounds like the original issue reported here is resolved.  I'm going to go ahead and close the issue.  Thanks.
