### ISSUE TITLE
HOLY JESUS

### ISSUE THREAD

**Issue by PowerMan2206** [NVIDIA/open-gpu-kernel-modules#4]
Extremely based move, Nvidia.

**Comment by aritger** [comment]
Thank you for your enthusiasm.  I'm going to go ahead and close this Issue.

Per our code of conduct: https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/CODE_OF_CONDUCT.md please keep try to refrain from expressions that might be interpreted as insulting.

**Comment by Muku784** [comment]
Thanks for closing, using religious terms is utterly appalling. Based move.
