### ISSUE TITLE
Dmesg NVRM messages on Dell Precision 7760

### ISSUE THREAD

**Issue by w5pny** [NVIDIA/open-gpu-kernel-modules#421]
### NVIDIA Open GPU Kernel Modules Version

525.60.11

### Does this happen with the proprietary driver (of the same version) as well?

Yes

### Operating System and Version

Ubuntu 20.04.5 LTS

### Kernel Release

Linux sirius 5.14.0-1054-oem #61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Hardware: GPU

GPU 0: NVIDIA RTX A3000 Laptop GPU (UUID: GPU-417ead46-fcb2-4593-f174-2f1cda4562be)

### Describe the bug

I have a Dell Precision 7760 Laptop with an Nvidia GPU.
It is running Ubumtu 20.04 LTS and was using the
Nvidie 520 driver (non-open).  When I did the upgrade
to 525 I went to the open kernel module version and
I had to add

options nvidia NVreg_OpenRmEnableUnsupportedGpus=1

to the /etc/modeprobe.d directory in order for
the nvidia utilities to work.

Things seem to work fine except that when booting 
I get the following in the demsg output:

[    1.792940] NVRM: loading NVIDIA UNIX Open Kernel Module for x86_64  525.60.11  Release Build  (dvs-builder@U16-T01-9-2)  Wed Nov 23 23:04:11 UTC 2022
[    1.924873] NVRM objClInitPcieChipset: *** Chipset Setup Function Error!

Since things seem to be working ok, I don't know of this is a bug or not...

nvidia-smi -q yields:

==============NVSMI LOG==============

Timestamp                                 : Sun Dec  4 17:42:13 2022
Driver Version                            : 525.60.11
CUDA Version                              : 12.0

Attached GPUs                             : 1
GPU 00000000:01:00.0
    Product Name                          : NVIDIA RTX A3000 Laptop GPU
    Product Brand                         : NVIDIA RTX
    Product Architecture                  : Ampere
    Display Mode                          : Disabled
    Display Active                        : Disabled
    Persistence Mode                      : Disabled
    MIG Mode
        Current                           : N/A
        Pending                           : N/A
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : N/A
        Pending                           : N/A
    Serial Number                         : N/A
    GPU UUID                              : GPU-417ead46-fcb2-4593-f174-2f1cda4562be
    Minor Number                          : 0
    VBIOS Version                         : 94.04.42.40.02
    MultiGPU Board                        : No
    Board ID                              : 0x100
    Board Part Number                     : N/A
    GPU Part Number                       : 24B8-926-A1
    Module ID                             : 0
    Inforom Version
        Image Version                     : G001.0000.03.03
        OEM Object                        : 2.0
        ECC Object                        : N/A
        Power Management Object           : N/A
    GPU Operation Mode
        Current                           : N/A
        Pending                           : N/A
    GSP Firmware Version                  : 525.60.11
    GPU Virtualization Mode
        Virtualization Mode               : None
        Host VGPU Mode                    : N/A
    IBMNPU
        Relaxed Ordering Mode             : N/A
    PCI
        Bus                               : 0x01
        Device                            : 0x00
        Domain                            : 0x0000
        Device Id                         : 0x24B810DE
        Bus Id                            : 00000000:01:00.0
        Sub System Id                     : 0x0A6A1028
        GPU Link Info
            PCIe Generation
                Max                       : 4
                Current                   : 2
                Device Current            : 2
                Device Max                : 4
                Host Max                  : 4
            Link Width
                Max                       : 16x
                Current                   : 8x
        Bridge Chip
            Type                          : N/A
            Firmware                      : N/A
        Replays Since Reset               : 0
        Replay Number Rollovers           : 0
        Tx Throughput                     : 186000 KB/s
        Rx Throughput                     : 0 KB/s
        Atomic Caps Inbound               : N/A
        Atomic Caps Outbound              : N/A
    Fan Speed                             : N/A
    Performance State                     : P5
    Clocks Throttle Reasons
        Idle                              : Active
        Applications Clocks Setting       : Not Active
        SW Power Cap                      : Not Active
        HW Slowdown                       : Not Active
            HW Thermal Slowdown           : Not Active
            HW Power Brake Slowdown       : Not Active
        Sync Boost                        : Not Active
        SW Thermal Slowdown               : Not Active
        Display Clock Setting             : Not Active
    FB Memory Usage
        Total                             : 6144 MiB
        Reserved                          : 349 MiB
        Used                              : 1424 MiB
        Free                              : 4369 MiB
    BAR1 Memory Usage
        Total                             : 8192 MiB
        Used                              : 7 MiB
        Free                              : 8185 MiB
    Compute Mode                          : Default
    Utilization
        Gpu                               : 35 %
        Memory                            : 13 %
        Encoder                           : 0 %
        Decoder                           : 0 %
    Encoder Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    FBC Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    Ecc Mode
        Current                           : N/A
        Pending                           : N/A
    ECC Errors
        Volatile
            SRAM Correctable              : N/A
            SRAM Uncorrectable            : N/A
            DRAM Correctable              : N/A
            DRAM Uncorrectable            : N/A
        Aggregate
            SRAM Correctable              : N/A
            SRAM Uncorrectable            : N/A
            DRAM Correctable              : N/A
            DRAM Uncorrectable            : N/A
    Retired Pages
        Single Bit ECC                    : N/A
        Double Bit ECC                    : N/A
        Pending Page Blacklist            : N/A
    Remapped Rows                         : N/A
    Temperature
        GPU Current Temp                  : 55 C
        GPU Shutdown Temp                 : 98 C
        GPU Slowdown Temp                 : 95 C
        GPU Max Operating Temp            : 87 C
        GPU Target Temperature            : N/A
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
    Power Readings
        Power Management                  : N/A
        Power Draw                        : 18.04 W
        Power Limit                       : N/A
        Default Power Limit               : N/A
        Enforced Power Limit              : N/A
        Min Power Limit                   : N/A
        Max Power Limit                   : N/A
    Clocks
        Graphics                          : 435 MHz
        SM                                : 435 MHz
        Memory                            : 810 MHz
        Video                             : 555 MHz
    Applications Clocks
        Graphics                          : 1560 MHz
        Memory                            : 5501 MHz
    Default Applications Clocks
        Graphics                          : 1560 MHz
        Memory                            : 5501 MHz
    Deferred Clocks
        Memory                            : N/A
    Max Clocks
        Graphics                          : 1740 MHz
        SM                                : 1740 MHz
        Memory                            : 5501 MHz
        Video                             : 1530 MHz
    Max Customer Boost Clocks
        Graphics                          : N/A
    Clock Policy
        Auto Boost                        : N/A
        Auto Boost Default                : N/A
    Voltage
        Graphics                          : 631.250 mV
    Fabric
        State                             : N/A
        Status                            : N/A
    Processes
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 41090
            Type                          : G
            Name                          : /usr/lib/xorg/Xorg
            Used GPU Memory               : 1070 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 41509
            Type                          : G
            Name                          : /usr/bin/kwin_x11
            Used GPU Memory               : 153 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 41514
            Type                          : G
            Name                          : /usr/bin/plasmashell
            Used GPU Memory               : 108 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 41681
            Type                          : G
            Name                          : /usr/bin/akonadi_archivemail_agent
            Used GPU Memory               : 3 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 41687
            Type                          : G
            Name                          : /usr/bin/akonadi_mailfilter_agent
            Used GPU Memory               : 3 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 41698
            Type                          : G
            Name                          : /usr/bin/akonadi_sendlater_agent
            Used GPU Memory               : 3 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 41699
            Type                          : G
            Name                          : /usr/bin/akonadi_unifiedmailbox_agent
            Used GPU Memory               : 75 MiB

### To Reproduce

Same dmesg NVRM messages appear with ever reboot. 

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/NVIDIA/open-gpu-kernel-modules/files/10150176/nvidia-bug-report.log.gz)

**Comment by w5pny** [comment]
Ubuntu just released 525.78.01 and this problem still exists with that version.

**Comment by mtijanic** [comment]
Hey there, thanks for the report!

    [ 1.792940] NVRM: loading NVIDIA UNIX Open Kernel Module for x86_64 525.60.11 Release Build (dvs-builder@U16-T01-9-2) Wed Nov 23 23:04:11 UTC 2022

This one is expected to be printed during normal operation, no worries there.

    [ 1.924873] NVRM objClInitPcieChipset: *** Chipset Setup Function Error!

This one is very unfortunately written. It comes up when we fail to apply some per-chipset specific hacks and workarounds. This can happen for two reasons:
1. The function that applies these hacks fails for some reason.
2. The chipset is not known to the driver

In your case, it's (2). You can see a list of known chipsets here:
https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/src/nvidia/arch/nvalloc/common/inc/nvcst.h#L101-L189
Tiger Lake is missing from that list. I'm not sure why, probably an oversight. I'll check.

If there are no special hacks to be applied to a given chipset, then this error message is harmless spam. AFAIK this is the case here.

However, it's good that you opened this issue as we really need to clean up this print. It shouldn't spam by default if the chipset is not found, and the error message should be clearer.

Since you report that everything is working, you shouldn't worry. And sorry for spamming your logs.

**Comment by w5pny** [comment]
Thanks for the update on this!  That explains the reason for NVRM message.  I have another message to nividia in the linux nvidia forum about the proprietary kernel
version on the 7760 though, since ever since 520, the proprietary kernel version
freezes on boot -- only the open kernel version works and I was thinking maybe the NVRM message I was getting was a reason for that as well.  I would think the proprietary kernel version should work as well....  So "evertyhing is working" is ONLY true for the open-kernel version!

**Comment by w5pny** [comment]
I mis-spoke above, the proprietary kernel version with the 7760 freezes on
boot ever since version 515, not 520.  510, was the last working proprietary
version.  The open-kernel version has always worked, except I needed to non-recognized gpu modprobe workaround for the nvidia tools to work with the open-kernel version, but that is now no longer required either with 525-78.

**Comment by w5pny** [comment]
See:

https://forums.developer.nvidia.com/t/525-60-11-proprietary-kernel-version-wont-boot-with-dell-precision-t7760-laptop/238763

**Comment by w5pny** [comment]
With 525.85.05 this issue seems to be resolved!
