### ISSUE TITLE
ASUS TUF Gaming A15 can't wake after sleep

### ISSUE THREAD

**Issue by TanawatJukmongkol** [NVIDIA/open-gpu-kernel-modules#422]
### NVIDIA Open GPU Kernel Modules Version

525.60.11

### Does this happen with the proprietary driver (of the same version) as well?

Yes

### Operating System and Version

Arch Linux

### Kernel Release

6.0.11-zen1-1-zen

### Hardware: GPU

NVIDIA GeForce RTX 3050 Laptop GPU

### Describe the bug

Cannot wake the laptop up after running `systemctl suspend`, or press the sleep button.

### To Reproduce

N/A

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/NVIDIA/open-gpu-kernel-modules/files/10151068/nvidia-bug-report.log.gz)

### More Info

> cat /sys/power/mem_sleep
$ [s2idle]
> cat /sys/power/state
$ freeze mem disk

**Comment by amrit1711** [comment]
Thanks for reporting issue to us, there is a bug 3908600 internally filed for tracking purpose and team is working on it.

**Comment by amrit1711** [comment]
Please test with driver 530.41.03 and share test results.

**Comment by TanawatJukmongkol** [comment]
Works wonderfully! Tried with both the sleep button, and `systemctl suspend`. Works both on Wayland and Xorg KDE-Plasma. Have not tested on Tiling WMs, but if there's any other issues related to this, or other issues arises I'll report right away! Closing this for now :)

**Comment by Xdavius** [comment]
> Thanks for reporting issue to us, there is a bug 3908600 internally filed for tracking purpose and team is working on it.

Hi. Re opening the issue with 610 or 595 driver on the same laptop...

This laptop is s2idle only.

I'm still trying to find a fix on my side...

Best regards
