### ISSUE TITLE
XRandR cannot see secondary display

### ISSUE THREAD

**Issue by RealAstolfo** [NVIDIA/open-gpu-kernel-modules#434]
### NVIDIA Open GPU Kernel Modules Version

N/A

### Does this happen with the proprietary driver (of the same version) as well?

Yes

### Operating System and Version

Description:    Gentoo Linux

### Kernel Release

Custom Build: Linux localhost 6.1.1-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC Sat Dec 24 15:44:32 MST 2022 x86_64 AMD Ryzen 7 5800X 8-Core Processor AuthenticAMD GNU/Linux

### Hardware: GPU

GPU 0: NVIDIA GeForce RTX 3060 Ti (UUID: GPU-75d66f6d-c201-7281-4fbf-8be24faf4e5c)

### Describe the bug

XRandR cannot detect secondary/ternary displays until the cable is unplugged from the gpu itself and moved to a _different_ display port/hdmi port. the entire port does not show up.

### To Reproduce

boot computer with both monitors plugged in

```sh
user$ xrandr
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 544mm x 303mm
   1920x1080     60.00 + 239.76*  143.98   119.98    59.94    50.00
   1600x900      60.00
   1280x1024     75.02    60.02
   1280x720      59.94    50.00
   1152x864      75.00
   1024x768      75.03    60.00
   800x600       75.00    60.32
   720x576       50.00
   720x480       59.94
   640x480       75.00    59.94    59.93
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
```
notice "DP-4" is missing completely

unplug cable from GPU, plug into another port
```sh
user$ xrandr
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 544mm x 303mm
   1920x1080     60.00 + 239.76*  143.98   119.98    59.94    50.00
   1600x900      60.00
   1280x1024     75.02    60.02
   1280x720      59.94    50.00
   1152x864      75.00
   1024x768      75.03    60.00
   800x600       75.00    60.32
   720x576       50.00
   720x480       59.94
   640x480       75.00    59.94    59.93
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected (normal left inverted right x axis y axis)
   2560x1080     59.98 +  99.94    74.99    50.00
   3840x2160     29.97    25.00    23.98
   1920x1080     60.00    59.94    50.00
   1280x720      59.94    50.00
   1024x768      60.00
   800x600       60.32
   720x576       50.00
   720x480       59.94
   640x480       59.94    59.93
DP-3 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
```

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/NVIDIA/open-gpu-kernel-modules/files/10326613/nvidia-bug-report.log.gz)

### More Info

xinerama is not enabled, because the graphics API's (both vulkan and OpenGL) fail to open the device to open something like a game. this would not have been an issue if the port simply acted like it never existed when booting

**Comment by aaronp24** [comment]
DP-4 is assigned to a second X screen. From your bug report log:
```
[     5.868] (II) NVIDIA(1): Validated MetaModes:
[     5.868] (II) NVIDIA(1):     "DFP-5:nvidia-auto-select"
```
You should be able to see it in xrandr by targeting the second X screen with `xrandr --screen 1`.

Do you actually want to have two X screens? From your bug report log it sounds like you don't. I'd recommend simplifying your xorg.conf to have a single screen with a MetaMode that specifies both display devices:
```
Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    Option         "metamodes" "DP-0: 1920x1080_240 +0+0, DP-2: 2560x1080_100 +1920+0 {rotation=right, AllowGSYNC=Off}"
EndSection
```
(delete everything else in xorg.conf, it's not necessary)

Closing as this isn't a bug and also isn't directly related to the open kernel modules. Please follow up on [the forum](https://forums.developer.nvidia.com/c/gpu-graphics/linux/148) if you need help configuring the server the way you want.
