### ISSUE TITLE
updating cuda driver lead to bus error

### ISSUE THREAD

**Issue by de1star** [NVIDIA/open-gpu-kernel-modules#476]
### NVIDIA Open GPU Kernel Modules Version

None

### Does this happen with the proprietary driver (of the same version) as well?

Yes

### Operating System and Version

CentOS Linux release 7.4.1708 (Core) 

### Kernel Release

None

### Hardware: GPU

NVIDIA A100-SXM4-80GB

### Describe the bug

Hi, we updated cuda driver from 520 to 525, cuda from 11.8 to 12.0 and ofed driver from 5.4 to 5.8, then bus error occured frequently. Some of my logs:   
![企业微信截图_16794158141234](https://user-images.githubusercontent.com/37529028/226695719-78648afb-0af8-42eb-b467-51800c2c1b3d.png)
![企业微信截图_1f39dd5d-5bfc-4d5d-a512-2348e81e6dc9](https://user-images.githubusercontent.com/37529028/226695741-138e2ddd-321f-4260-a728-b33734956026.png)
![企业微信截图_16793951607858](https://user-images.githubusercontent.com/37529028/226695770-23da175b-623a-4bf0-8506-36a92c10c765.png)
Could you provide some suggestions?

### To Reproduce

We were running pytorch codes so it's hard to provide a reproduction scripts for you.

### Bug Incidence

Always

### nvidia-bug-report.log.gz

I will attach that later after I run nvidia-bug-report.sh.

**Comment by amrit1711** [comment]
@de1star 
I would request you to post issue on Linux Forum with reliable repro steps so that we can try to duplicate issue locally first and then can go ahead with debugging.
https://forums.developer.nvidia.com/c/gpu-graphics/linux/148
Since this forum is restricted to open kernel modules, I will close this thread.
