### ISSUE TITLE
Question about cross_compile the kernel module

### ISSUE THREAD

**Issue by shumeigiku** [NVIDIA/open-gpu-kernel-modules#504]
### NVIDIA Open GPU Kernel Modules Version

525.47.26

### Operating System and Version

Ubuntu 20.04.3 LTS

### Kernel Release

5.15.0-56-generic

### Build Command

make modules -j8        \
    TARGET_ARCH=aarch64         \
    CC=aarch64-linux-gnu-gcc    \
    LD=aarch64-linux-gnu-ld     \
    AR=aarch64-linux-gnu-ar     \
    CXX=aarch64-linux-gnu-g++   \
    OBJCOPY=aarch64-linux-gnu-objcopy

### Terminal output/Build Log

...
make[1]: Leaving directory 'open-gpu-kernel-modules-525.47.26/src/nvidia'
cd kernel-open/nvidia/ && ln -sf ../../src/nvidia/_out/Linux_aarch64/nv-kernel.o nv-kernel.o_binary
make -C kernel-open modules
make[1]: Entering directory 'open-gpu-kernel-modules-525.47.26/kernel-open'
make[2]: Entering directory '/usr/src/linux-headers-5.15.0-56-generic'
arch/x86/Makefile:142: CONFIG_X86_X32 enabled but no binutils support
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 9.4.0-1 ubuntu1~20.04.1) 9.4.0

  You are using:           aarch64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
aarch64-linux-gnu-gcc: error: unrecognized argument in option ‘-mcmodel=kernel’
aarch64-linux-gnu-gcc: note: valid arguments to ‘-mcmodel=’ are: large small tiny
...

### More Info

I want to build a NVIDIA kernel module in a Ubuntu Host, then burn it (together with a  Linux OS v5.3.0) into an Arm device. However, it fails to compile and report the bug above.

Can someone help me? If better, can someone tell me how to load the module into the Linux OS running for the Arm device?

**Comment by aritger** [comment]
It looks like the target kernel you are building for was built for x86, not aarch64?  (the "arch/x86/Makefile" after recursing into kbuild).  I suspect that is where the `-mcmodel` argument is coming from.  Could you double check that you've built your target kernel for aarch64?  You may need to set SYSSRC to tell the open-gpu-kernel-modules Makefiles where your target kernel is.

**Comment by shumeigiku** [comment]
> It looks like the target kernel you are building for was built for x86, not aarch64? (the "arch/x86/Makefile" after recursing into kbuild). I suspect that is where the `-mcmodel` argument is coming from. Could you double check that you've built your target kernel for aarch64? You may need to set SYSSRC to tell the open-gpu-kernel-modules Makefiles where your target kernel is.

Thanks for your reply, but do we have manuals for compiling? I do not set the SYSSRC during the compiling, just follow the cmd in the readme.

Could you give some advice?

**Comment by aritger** [comment]
I think the first step would be to cross-compile the Linux kernel.  Cross-compiling the NVIDIA kernel modules would be a modest incremental step after that.  There are a number of tutorials online for cross-compiling the kernel.  Here is one: https://gts3.org/2017/cross-kernel.html

**Comment by aritger** [comment]
I don't have a lot of firsthand experience with cross-compiling.  But:

1. To install the kernel modules into target OS image, you could copy them manually, or use `make modules_install` in a way similar to how I imagine you're installing your kernel's in-tree modules into the OS image?  Does `O=` help, like described here?  https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/README.rst#build-directory-for-the-kernel
2. The same kernel modules support A16 and GTX/RTX GPUs.

**Comment by shumeigiku** [comment]
Many thanks. I think I can close this issue.
