### ISSUE TITLE
Issue building under debian 12

### ISSUE THREAD

**Issue by DT3264** [NVIDIA/open-gpu-kernel-modules#516]
### NVIDIA Open GPU Kernel Modules Version

525.105.17

### Operating System and Version

Debian 12

### Kernel Release

6.1.31

### Build Command

make modules

### Terminal output/Build Log

make -C src/nvidia
make[1]: Entering directory '/tmp/lab-2767/open-gpu-kernel-modules/src/nvidia'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/tmp/lab-2767/open-gpu-kernel-modules/src/nvidia'
cd kernel-open/nvidia/ && ln -sf ../../src/nvidia/_out/Linux_x86_64/nv-kernel.o nv-kernel.o_binary
make -C src/nvidia-modeset
make[1]: Entering directory '/tmp/lab-2767/open-gpu-kernel-modules/src/nvidia-modeset'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/tmp/lab-2767/open-gpu-kernel-modules/src/nvidia-modeset'
cd kernel-open/nvidia-modeset/ && ln -sf ../../src/nvidia-modeset/_out/Linux_x86_64/nv-modeset-kernel.o nv-modeset-kernel.o_binary
make -C kernel-open modules
make[1]: Entering directory '/tmp/lab-2767/open-gpu-kernel-modules/kernel-open'
make[2]: Entering directory '/tmp/lab-2767/linux'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Debian 12.2.0-14) 12.2.0
  You are using:           cc (Debian 12.2.0-14) 12.2.0
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_channel.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_lock.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_hal.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_range_tree.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_rb_tree.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_range_allocator.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_va_range.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_va_policy.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_va_block.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_range_group.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_gpu_replayable_faults.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_gpu_non_replayable_faults.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_gpu_access_counters.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_perf_events.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_perf_module.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_mmu.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pte_batch.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_tlb_batch.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_push.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pushbuffer.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_thread_context.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_tracker.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_maxwell.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_maxwell_host.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_maxwell_ce.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_maxwell_mmu.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_maxwell_fault_buffer.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_maxwell_access_counter_buffer.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pascal.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pascal_ce.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pascal_host.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pascal_mmu.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pascal_fault_buffer.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_volta_ce.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_volta_host.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_volta_mmu.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_volta.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_volta_fault_buffer.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_volta_access_counter_buffer.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_turing.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_turing_access_counter_buffer.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_turing_fault_buffer.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_turing_mmu.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_turing_host.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_ampere.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_ampere_ce.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_ampere_host.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_ampere_mmu.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_hopper.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_hopper_fault_buffer.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_hopper_ce.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_hopper_host.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_hopper_mmu.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_ada.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_policy.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_perf_utils.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_kvmalloc.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pmm_sysmem.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pmm_gpu.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_migrate.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_populate_pageable.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_migrate_pageable.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_map_external.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_user_channel.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_hmm.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_perf_heuristics.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_perf_thrashing.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_perf_prefetch.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_ats.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_ats_ibm.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_ats_faults.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_test_rng.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_range_tree_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_range_allocator_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_gpu_semaphore_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_mem_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_rm_mem_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_page_tree_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_tracker_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_push_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_channel_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_ce_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_host_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_lock_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_perf_utils_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_kvmalloc_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pmm_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_pmm_sysmem_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_perf_events_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_perf_module_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_get_rm_ptes_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_fault_buffer_flush_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_peer_identity_mappings_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_va_block_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_range_group_tree_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_thread_context_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_rb_tree_test.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm/uvm_rm_mem.o
  LD [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-modeset/nvidia-modeset-linux.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-modeset/nv-kthread-q.o
  LD [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-modeset.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-drv.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-utils.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-crtc.o
/tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-crtc.c: In function ‘__nv_drm_plane_atomic_destroy_state’:
/tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-crtc.c:695:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  695 |     struct nv_drm_plane_state *nv_drm_plane_state =
      |     ^~~~~~
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-encoder.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-connector.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-gem.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-fb.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-modeset.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-fence.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-linux.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-helper.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nv-pci-table.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-gem-nvkms-memory.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-gem-user-memory.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-gem-dma-buf.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm/nvidia-drm-format.o
  LD [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm.o
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-peermem/nvidia-peermem.o
  LD [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-peermem.o
ld -r -o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-interface.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-pci.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-dmabuf.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-nano-timer.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-acpi.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-cray.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-dma.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-i2c.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-mmap.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-p2p.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-pat.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-procfs.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-usermap.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-vm.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-vtophys.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/os-interface.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/os-mlock.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/os-pci.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/os-registry.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/os-usermap.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-modeset-interface.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-pci-table.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-kthread-q.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-memdbg.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-ibmnpu.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-report-err.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-rsync.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-msi.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-caps.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv-frontend.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nv_uvm_interface.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nvlink_linux.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/nvlink_caps.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/linux_nvswitch.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/procfs_nvswitch.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia/i2c_nvswitch.o
ld -r -o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-modeset/nv-modeset-interface.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-modeset/nvidia-modeset-linux.o /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-modeset/nv-kthread-q.o
  MODPOST /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/Module.symvers
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm.mod.o
  LD [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-drm.ko
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-modeset.mod.o
  LD [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-modeset.ko
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-peermem.mod.o
  LD [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-peermem.ko
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm.mod.o
  LD [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia-uvm.ko
  CC [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia.mod.o
  LD [M]  /tmp/lab-2767/open-gpu-kernel-modules/kernel-open/nvidia.ko
make[2]: Leaving directory '/tmp/lab-2767/linux'
make[1]: Leaving directory '/tmp/lab-2767/open-gpu-kernel-modules/kernel-open'

### More Info

The same output happens if I try to install the kernel modules from [the .run files](https://download.nvidia.com/XFree86/Linux-x86_64/525.105.17/), 
I'm not sure what might be the culprit, but if I install the [debian nvidia-kernel-dkms](https://packages.debian.org/bookworm/nvidia-kernel-dkms) package, the kernel module gets compiled with no issues.

**Comment by aritger** [comment]
While we should fix this, it looks like it is only a compiler warning, correct?  This isn't preventing driver installation, right?

Does the following patch resolve the warning for you?
```
--- a/kernel-open/nvidia-drm/nvidia-drm-crtc.c
+++ b/kernel-open/nvidia-drm/nvidia-drm-crtc.c
@@ -692,9 +692,11 @@ static inline void __nv_drm_plane_atomic_destroy_state(
 #endif
 
 #if defined(NV_DRM_HAS_HDR_OUTPUT_METADATA)
-    struct nv_drm_plane_state *nv_drm_plane_state =
-        to_nv_drm_plane_state(state);
-    drm_property_blob_put(nv_drm_plane_state->hdr_output_metadata);
+    {
+        struct nv_drm_plane_state *nv_drm_plane_state =
+            to_nv_drm_plane_state(state);
+        drm_property_blob_put(nv_drm_plane_state->hdr_output_metadata);
+    }
 #endif
 }
```
