### ISSUE TITLE
Older Minecraft versions are broken with the 535.54.03 driver

### ISSUE THREAD

**Issue by Tarballwalf** [NVIDIA/open-gpu-kernel-modules#522]
### NVIDIA Open GPU Kernel Modules Version

535.54.03

### Does this happen with the proprietary driver (of the same version) as well?

Yes

### Operating System and Version

EndeavourOS Linux

### Kernel Release

Linux TUF-F15 6.3.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:07 +0000 x86_64 GNU/Linux

### Hardware: GPU

NVIDIA GeForce RTX 3060 Laptop GPU

### Describe the bug

The issue appeared as soon as I updated to 535.43.03 proprietary driver, later on I tried to see if this happens with the open kernel modules, and it indeed happens. 

**Words cannot describe what I saw**
But I'll try to sum it up. **Really** broken textures, sometimes they start to flicker. Resizing the window makes them go even crazier.

See attached screenshots
![Screenshot_20230623_124433](https://github.com/NVIDIA/open-gpu-kernel-modules/assets/56345519/61101557-cf12-4ea1-a90c-74f94165e732)
![Screenshot_20230623_124419](https://github.com/NVIDIA/open-gpu-kernel-modules/assets/56345519/0d44f4d9-8a1c-4e78-ae3c-62b364c00bb9)
![Screenshot_20230623_124413](https://github.com/NVIDIA/open-gpu-kernel-modules/assets/56345519/1b4db7a8-f4ce-44ca-ab19-8ca662f9f4ca)
![Screenshot_20230623_124403](https://github.com/NVIDIA/open-gpu-kernel-modules/assets/56345519/cf703adb-e09c-4930-bec6-c1b407e5b224)
![Screenshot_20230623_124358](https://github.com/NVIDIA/open-gpu-kernel-modules/assets/56345519/a04d2d8f-d4af-4ea6-b891-e21fc6bbcac9)
![Screenshot_20230623_124351](https://github.com/NVIDIA/open-gpu-kernel-modules/assets/56345519/b6b2232e-de5b-4fe7-85a7-f15b9564dc2a)
![Screenshot_20230623_124337](https://github.com/NVIDIA/open-gpu-kernel-modules/assets/56345519/5f3978a8-1461-44e7-ac8f-0b4cb70ea596)

### To Reproduce

Open older Minecraft versions running java 8 (other people pointed out it’s because of LWJGL 2). Modded or not

### Bug Incidence

Always

### nvidia-bug-report.log.gz

Bug report is so large (almost 2 million lines), I have to upload it here as a file
[nvidia-bug-report.log.gz](https://github.com/NVIDIA/open-gpu-kernel-modules/files/11847316/nvidia-bug-report.log.gz)

### More Info

The issue does not seem to be related to X11 or Wayland. This happens on both.

EDIT: Forgot to state, that the game works as expect on the Intel IGP.

**Comment by vova7865** [comment]
Can confirm, this appears to affect Minecraft versions 13w41a to 1.12.2. Does not seem to affect versions 13w39b and below, or 17w43a and above. Minecraft switched to LWJGL 3.1.2 in 17w43a, however, both 13w39b and 13w41a use LWJGL 2.9.4-nightly-20150209.

**Comment by ttabi** [comment]
I don't know anything about LWJGL, but it seems to me that "LWJGL 2.9.4-**nightly**-20150209" is a nightly, unstable build.  It looks like this was a bug in LWJGL that was fixed.  What are you expecting Nvidia to do about it?

**Comment by Lolothepro** [comment]
This version of the driver also crashes Minecraft in certain situations.

**Comment by Lolothepro** [comment]
workaround: __GL_THREADED_OPTIMIZATIONS=0

**Comment by Tarballwalf** [comment]
> workaround: __GL_THREADED_OPTIMIZATIONS=0

It indeed works. 
You're a lifesaver, after kernel 6.4 NVIDIA 530 drivers stopped working.

**Comment by FelipeFMA** [comment]
> workaround: __GL_THREADED_OPTIMIZATIONS=0

what exactly is the workaround? where do i need to put this?

**Comment by ErrorNoInternet** [comment]
> > workaround: __GL_THREADED_OPTIMIZATIONS=0
> 
> what exactly is the workaround? where do i need to put this?

It's an environment variable, you can put it in /etc/environment to apply it globally or do `__GL_THREADED_OPTIMIZATIONS=0 minecraft-launcher`.

**Comment by FelipeFMA** [comment]
> > > workaround: __GL_THREADED_OPTIMIZATIONS=0
> > 
> > 
> > what exactly is the workaround? where do i need to put this?
> 
> It's an environment variable, you can put it in /etc/environment to apply it globally or do `__GL_THREADED_OPTIMIZATIONS=0 minecraft-launcher`.

it works, thank you

**Comment by Guanran928** [comment]
Can confirm this issue on driver version 535.xx, the glitch happens in Minecraft version 13w41a to 1.12.2 (including both version), downgrading the driver to 530.41.03 fixed this for me, so I am assuming it was NVIDIA.

**Comment by Lolothepro** [comment]
> I don't know anything about LWJGL, but it seems to me that "LWJGL 2.9.4-**nightly**-20150209" is a nightly, unstable build. It looks like this was a bug in LWJGL that was fixed. What are you expecting Nvidia to do about it?

That's not true, this version of LWJGL is stable, it's just that NVIDIA checks that liblwjgl64.so or liblwjgl.so is loaded to apply the optimization that creates the graphics corruptions, but these versions of LWJGL are not detected by the driver.

**Comment by RockyRoad65** [comment]
> It's an environment variable, you can put it in /etc/environment to apply it globally or do `__GL_THREADED_OPTIMIZATIONS=0 minecraft-launcher`.

When I try running __GL_THREADED_OPTIMIZATIONS=0 minecraft-launcher when I try to launch older versions it crashes when it tries to launch I get an error "The game crashed whilst initializing game
Error: org.lwjgl.LWJGLException: X Error - disp: 0x7f9de49ac130 serial: 157 error: BadValue (integer parameter out of range for operation) request_code: 152 minor_code: 24" On newer versions that were previously unaffected it now doesn't work either.
![Screenshot_2023-08-12_12-02-41](https://github.com/NVIDIA/open-gpu-kernel-modules/assets/108962763/12f86ba1-75ed-4f08-a5f1-2a51a4803bd5)

**Comment by OilFreak** [comment]
> > > workaround: __GL_THREADED_OPTIMIZATIONS=0
> > 
> > 
> > what exactly is the workaround? where do i need to put this?
> 
> It's an environment variable, you can put it in /etc/environment to apply it globally or do `__GL_THREADED_OPTIMIZATIONS=0 minecraft-launcher`.

any way to do this with multi mc?

**Comment by Tarballwalf** [comment]
> > > > workaround: __GL_THREADED_OPTIMIZATIONS=0
> > > 
> > > 
> > > what exactly is the workaround? where do i need to put this?
> > 
> > 
> > It's an environment variable, you can put it in /etc/environment to apply it globally or do `__GL_THREADED_OPTIMIZATIONS=0 minecraft-launcher`.
> 
> any way to do this with multi mc?
`env __GL_THREADED_OPTIMIZATIONS=0` in wrapper command

**Comment by OilFreak** [comment]
Ig i'm more asking how to launch Multi Mc from terminal.

**Comment by Guanran928** [comment]
> > > > workaround: __GL_THREADED_OPTIMIZATIONS=0
> > > 
> > > 
> > > what exactly is the workaround? where do i need to put this?
> > 
> > 
> > It's an environment variable, you can put it in /etc/environment to apply it globally or do `__GL_THREADED_OPTIMIZATIONS=0 minecraft-launcher`.
> 
> any way to do this with multi mc?

https://wiki.archlinux.org/title/Environment_variables

**Comment by OilFreak** [comment]
running pop_os.

**Comment by OilFreak** [comment]
> `env __GL_THREADED_OPTIMIZATIONS=0` in wrapper command
this worked yesterday and today it doesn't

**Comment by Nixuge** [comment]
> Ig i'm more asking how to launch Multi Mc from terminal.

With prism launcher (multimc fork) you just have to run prismlauncher, i guess it'd be the same for multimc @OilFreak

**Comment by Tortillas-IT** [comment]
with the new drivers (545.29.02) the issue is now fixed

**Comment by Tarballwalf** [comment]
I guess I can close this issue now
