### ISSUE TITLE
"Unrecognized AMD processor in cpuidInfoAMD" with AMD Ryzen 9 5950X

### ISSUE THREAD

**Issue by notpentadactyl** [NVIDIA/open-gpu-kernel-modules#534]
### NVIDIA Open GPU Kernel Modules Version

535.86.05

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [X] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

Arch Linux

### Kernel Release

6.4.3-273-tkg-cfs (self build)

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [X] I am running on a stable kernel release.

### Hardware: GPU

NVIDIA GeForce RTX 3080

### Describe the bug

`dmesg` prints `NVRM cpuidInfoAMD: Unrecognized AMD processor in cpuidInfoAMD` on boot when running on a system with an AMD Ryzen 9 5950X CPU.

### To Reproduce

Boot the system with an AMD Ryzen 9 5950X CPU.

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/NVIDIA/open-gpu-kernel-modules/files/12093652/nvidia-bug-report.log.gz)

**Comment by cemkaya-mpi** [comment]
I have the same error message with a Ryzen 6800H.

**Comment by s3rgeym** [comment]
I'm getting random freezes when watching videos on my ryzen 5600h/rtx 3060. I think it's an nvidia bug because the video uses hardware acceleration. And i have a same error

**Comment by kabasset** [comment]
I have the same error with an AMD Ryzen 5600 and RTX 3050. The only way to boot is in recovery mode.

**Comment by notpentadactyl** [comment]
This is fixed in `550.40.07` (looking at git it was already fixed in `545.23.06`).
