### ISSUE TITLE
Copy paste bug inside `dp_connectorimpl.cpp`

### ISSUE THREAD

**Issue by qarmin** [NVIDIA/open-gpu-kernel-modules#54]
**NVIDIA Driver Version**
Git version

https://github.com/NVIDIA/open-gpu-kernel-modules/blob/69791e9bf5161c786d620312fd6396756c37cff9/src/common/displayport/src/dp_connectorimpl.cpp#L1759-L1767

Value of `dscInfo->sinkCaps.bitsPerPixelPrecision` is overriden in next line

**Comment by PAR2020** [comment]
Internal bug 3643074

**Comment by PAR2020** [comment]
Resolved in PR #61
