### ISSUE TITLE
Copy paste bug in `osapi.c`

### ISSUE THREAD

**Issue by qarmin** [NVIDIA/open-gpu-kernel-modules#55]
**NVIDIA Driver Version**
Git 

https://github.com/NVIDIA/open-gpu-kernel-modules/blob/69791e9bf5161c786d620312fd6396756c37cff9/src/nvidia/arch/nvalloc/unix/src/osapi.c#L4589

`pNumaMemAddr` is checked twice if is equal to null

**Comment by Benedani** [comment]
Is it supposed to be pNumaMemSize? That's the one that isn't checked for null.

**Comment by PAR2020** [comment]
Internal bug 3643074

**Comment by PAR2020** [comment]
Resolved in PR #61 initially.
