### ISSUE TITLE
Copy paste bug in `dp_configcaps.cpp`

### ISSUE THREAD

**Issue by qarmin** [NVIDIA/open-gpu-kernel-modules#56]
**NVIDIA Driver Version**
Git

https://github.com/NVIDIA/open-gpu-kernel-modules/blob/69791e9bf5161c786d620312fd6396756c37cff9/src/common/displayport/src/dp_configcaps.cpp#L2866

Second check should be probably `bLinkActive`

**Comment by PAR2020** [comment]
Internal bug 3643074

**Comment by PAR2020** [comment]
Resolved in PR #61
