### ISSUE TITLE
550.76 release missing

### ISSUE THREAD

**Issue by sndirsch** [NVIDIA/open-gpu-kernel-modules#624]
### NVIDIA Open GPU Kernel Modules Version

550.67

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [ ] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

Linux

### Kernel Release

5.14.21

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [ ] I am running on a stable kernel release.

### Hardware: GPU

Turing

### Describe the bug

Driver release 550.76 has been happened on April 16. Could you make an appropriate version of the open driver as well, please? thanks!

### To Reproduce

Not needed

### Bug Incidence

Once

### nvidia-bug-report.log.gz

Not neeed

**Comment by niv** [comment]
Done now. :)
