### ISSUE TITLE
open-gpu-kerenel-modules can't build on kernel-6.10 after 2024-05-20

### ISSUE THREAD

**Issue by amie1972** [NVIDIA/open-gpu-kernel-modules#646]
### NVIDIA Open GPU Kernel Modules Version

555.42.02

### Operating System and Version

Fedora 41

### Kernel Release

6.10.0-0.rc0.20240523gitc760b3725e52.12.fc41.x86_64

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [ ] I am running on a stable kernel release.

### Build Command

make modules

### Terminal output/Build Log

error

**Comment by gauravjuvekar** [comment]
We do not support unreleased (rc) kernels.
