### ISSUE TITLE
please open legacy 340.xx drivers

### ISSUE THREAD

**Issue by gmankab** [NVIDIA/open-gpu-kernel-modules#65]

**Comment by aaronp24** [comment]
Thank you for your interest in the NVIDIA drivers. We currently have no plans to release source code to older versions.

**Comment by prorounak2005** [comment]
F

**Comment by dennismayr** [comment]
I guess we'll stick to Mesa, hoping that reverse-engineering by Red Hat yields good results.

**Comment by mb-real** [comment]
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffU
