### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by stensonb** [NVIDIA/open-gpu-kernel-modules#66]
Thanks for the effort to open source this.  To clarify the intent and future use here, can we get an official LICENCE.md file here as well?

BSD or MIT would be excellent.

**Comment by stensonb** [comment]
Ha...should have looked around a bit.  :)

**Comment by MedzikUser** [comment]
https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/COPYING
