### ISSUE TITLE
Cufft GPU memoey increase

### ISSUE THREAD

**Issue by GuangPanSir** [NVIDIA/open-gpu-kernel-modules#674]
### NVIDIA Open GPU Kernel Modules Version

11.8

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [X] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

Windows

### Kernel Release

no

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [X] I am running on a stable kernel release.

### Hardware: GPU

NVIDIA GeForce RTX 4060 Laptop GPU

### Describe the bug

When I loop through the following code, the GPU memory continues to increase 0.7G-->0.8G-------->1.6G

#include <iostream>
#include <cuda_runtime.h>
#include "device_launch_parameters.h"
#include <cufft.h>

#define CHECK_CUFFT_ERROR(call) {                                     \
    cufftResult err = call;                                           \
    if (err != CUFFT_SUCCESS) {                                       \
        std::cerr << "CUFFT error: " << err << std::endl;             \
        exit(1);                                                      \
    }                                                                 \
}

int main(){
    for (int i = 0; i < 100000; i++) {
        int width = 512;
        int height = 512;
        cufftHandle planR2C, planC2R;
        cufftPlan2d(&planR2C, height, width, CUFFT_R2C);
        cufftPlan2d(&planC2R, height, width, CUFFT_C2R);
        CHECK_CUFFT_ERROR(cufftDestroy(planR2C));
        CHECK_CUFFT_ERROR(cufftDestroy(planC2R));
    }

}

### To Reproduce

#include <iostream>
#include <cuda_runtime.h>
#include "device_launch_parameters.h"
#include <cufft.h>

#define CHECK_CUFFT_ERROR(call) {                                     \
    cufftResult err = call;                                           \
    if (err != CUFFT_SUCCESS) {                                       \
        std::cerr << "CUFFT error: " << err << std::endl;             \
        exit(1);                                                      \
    }                                                                 \
}

int main(){
    for (int i = 0; i < 100000; i++) {
        int width = 512;
        int height = 512;
        cufftHandle planR2C, planC2R;
        cufftPlan2d(&planR2C, height, width, CUFFT_R2C);
        cufftPlan2d(&planC2R, height, width, CUFFT_C2R);
        CHECK_CUFFT_ERROR(cufftDestroy(planR2C));
        CHECK_CUFFT_ERROR(cufftDestroy(planC2R));
    }

}

### Bug Incidence

Always

### nvidia-bug-report.log.gz

When I loop through the following code, the GPU memory continues to increase 0.7G-->0.8G-------->1.6G

#include <iostream>
#include <cuda_runtime.h>
#include "device_launch_parameters.h"
#include <cufft.h>

#define CHECK_CUFFT_ERROR(call) {                                     \
    cufftResult err = call;                                           \
    if (err != CUFFT_SUCCESS) {                                       \
        std::cerr << "CUFFT error: " << err << std::endl;             \
        exit(1);                                                      \
    }                                                                 \
}

int main(){
    for (int i = 0; i < 100000; i++) {
        int width = 512;
        int height = 512;
        cufftHandle planR2C, planC2R;
        cufftPlan2d(&planR2C, height, width, CUFFT_R2C);
        cufftPlan2d(&planC2R, height, width, CUFFT_C2R);
        CHECK_CUFFT_ERROR(cufftDestroy(planR2C));
        CHECK_CUFFT_ERROR(cufftDestroy(planC2R));
    }

}

**Comment by mtijanic** [comment]
See here for how to report CUDA bugs: https://developer.nvidia.com/cuda-faq

This is _really_ not the right place for it.
