### ISSUE TITLE
Vboost Print Output is Wrong

### ISSUE THREAD

**Issue by OrenLeung** [NVIDIA/open-gpu-kernel-modules#684]
### NVIDIA Open GPU Kernel Modules Version

550.90.07 

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [ ] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

Description:  Ubuntu 22.04.4 LTS

### Kernel Release

Linux node-1 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [x] I am running on a stable kernel release.

### Hardware: GPU

NVIDIA H100 80GB HBM3 

### Describe the bug

The output of vboost always displays `Successfully set vboost slider ` for only `GPU 0` even though i am querying for `GPU 0,1,2`

when i do `nvidia-smi boost-slider --list` , i can see that 0,1,2 is is correctly changed.

### To Reproduce

```bash
sudo nvidia-smi boost-slider -i 0,1,2 --vboost 2
Successfully set vboost slider with value 2 for GPU 0
Successfully set vboost slider with value 2 for GPU 0
Successfully set vboost slider with value 2 for GPU 0
```

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/16419203/nvidia-bug-report.log.gz)

**Comment by mtijanic** [comment]
Hey there. nvidia-smi is a few steps removed from the kernel modules so it's best to report these issues on the forum https://forums.developer.nvidia.com/c/gpu-graphics/linux/148 or send them to linux-bugs@nvidia.com

Closing this as there's no action on the kernel modules side.
