### ISSUE TITLE
add support for Quadro K2100M because it doesn't work with 390xx 340xx 418xx 

### ISSUE THREAD

**Issue by AnasSae-ed** [NVIDIA/open-gpu-kernel-modules#76]
add support for Quadro K2100M. it doesn't work with "340xx,390xx,418xx" but it works with "470xx(doesn't support Quadro K2100M)" how is that possible? the latest driver supports Quadro K2200M just minus 100. it won't hurt
or just fix the legacy drivers

**Comment by mtijanic** [comment]
Hello and thank you for your interest. As covered in the readme and in more detail [here](https://github.com/NVIDIA/open-gpu-kernel-modules/issues/19#issuecomment-1124360887), this driver architecture depends on hardware only present on Turing and later.

I've pinned #19 to consolidate all the relevant supported GPUs information, so I'll go ahead and close this one as a duplicate.
