### ISSUE TITLE
Port to HolyC (TempleOS)

### ISSUE THREAD

**Issue by alcaparra** [NVIDIA/open-gpu-kernel-modules#97]
Would it be possible to port this module into HolyC?
Nvidia driver support for TempleOS has been long awaited by the community, and both projects would benefit greatly.
Please consider this.

**Comment by TheRealOne78** [comment]
I wonder how much time people will make jokes about nvidia drivers

**Comment by alcaparra** [comment]
Also note that video output should be capped at 640x480 (divine resolution)

**Comment by niv** [comment]
Humour is fine and appreciated, but let's keep the issue repository as noise-free as possible so that it doesn't interfere with actual reports. Thanks.

**Comment by qkweint** [comment]
So refreshing to see this.

**Comment by TheKozax** [comment]
we need this!
